# Generated by Django 5.2.6 on 2026-01-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comments_author_comments_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
