# Generated by Django 5.2.6 on 2026-01-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments_author_posts_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
