# Generated by Django 6.0 on 2026-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
