# Generated by Django 6.0 on 2026-01-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_posts_updated_on_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
