# Generated by Django 5.2.6 on 2026-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_sacco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
