# Generated by Django 5.2.6 on 2026-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_sacco', '0003_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
