# Generated by Django 5.2.6 on 2025-12-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
